#
# see:
# <Effective Dart> https://dart.dev/guides/language/effective-dart
# <pedantic> https://pub.dev/packages/pedantic
# <lint> https://pub.dev/packages/lint
#
linter:
  rules:
    #
    # Style
    #
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_empty_else
    # avoid_escaping_inner_quotes: unnecessary
    - avoid_field_initializers_in_const_classes
    - avoid_implementing_value_types
    - avoid_redundant_argument_values
    - avoid_returning_null_for_void
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    # avoid_void_async: if we need do something async without await, it may conflict with [unawaited_futures]
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_catches
    - exhaustive_cases
    - file_names
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    # lines_longer_than_80_chars: we prefer 100 chars per line at most
    # missing_whitespace_between_adjacent_strings: unnecessary
    - non_constant_identifier_names
    - no_duplicate_case_values
    - no_runtimeType_toString
    - null_closures
    - overridden_fields
    - package_prefixed_library_names
    # parameter_assignments: unnecessary
    - prefer_asserts_in_initializer_lists
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    # prefer_constructors_over_static_methods: we need to use some local variables in static method before create object
    - prefer_contains
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_inlined_adds
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - provide_deprecation_message
    - recursive_getters
    - sized_box_for_whitespace
    # sort_child_properties_last: unnecessary, if we can fix hundreds issues before
    - sort_unnamed_constructors_first
    - unawaited_futures
    # unnecessary_await_in_return: unnecessary, if we can fix hundreds issues before
    - unnecessary_null_aware_assignments
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    # unnecessary_string_escapes: unnecessary
    - unnecessary_string_interpolations
    - use_full_hex_values_for_flutter_colors
    - use_string_buffers
    - void_checks

    #
    # Documentation
    #
    # comment_references: unnecessary
    - package_api_docs
    # public_member_api_docs: unnecessary
    - slash_for_doc_comments

    #
    # Usage
    #
    # avoid_catches_without_on_clauses: unnecessary
    - avoid_catching_errors
    # avoid_function_literals_in_foreach_calls: unnecessary
    - avoid_init_to_null
    - avoid_relative_lib_imports
    - empty_constructor_bodies
    # implementation_imports: unnecessary
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_equal_for_default_values
    # prefer_expression_function_bodies: unnecessary
    - prefer_function_declarations_over_variables
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_iterable_whereType
    # prefer_relative_imports: we prefer absolutely imports
    - type_init_formals
    # unnecessary_brace_in_string_interps: unnecessary
    - unnecessary_const
    # unnecessary_getters_setters: unnecessary
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - valid_regexps

    #
    # Design
    #
    # avoid_classes_with_only_static_members: unnecessary
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_null_checks_in_equality_operators
    # avoid_positional_boolean_parameters: unnecessary
    - avoid_private_typedef_functions
    # avoid_returning_null: unnecessary
    - avoid_returning_this
    - avoid_return_types_on_setters
    # avoid_setters_without_getters: unnecessary
    # avoid_types_on_closure_parameters: unnecessary
    - hash_and_equals
    # omit_local_variable_types: unnecessary
    # one_member_abstracts: unnecessary
    - prefer_final_fields
    - prefer_generic_function_type_aliases
    # prefer_mixin: unnecessary
    - prefer_typing_uninitialized_variables
    - type_annotate_public_apis
    - use_function_type_syntax_for_parameters
    # use_setters_to_change_properties: unnecessary
    - use_to_and_as_if_applicable

    #
    # Errors
    #
    # avoid_print: unnecessary, we need print in unit test
    - avoid_returning_null_for_future
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - control_flow_in_finally
    - empty_statements
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
    - no_logic_in_create_state
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unsafe_html

    #
    # Pub
    #
    - package_names
    # sort_pub_dependencies: unnecessary